language: node_js

node_js:
  - node

before_install:
  # - npm i -g polymer-cli
  - npm i -g firebase-tools
  - npm i -g bower
  - cd public
  - git clone https://github.com/interlucid/web-audio-api

install:
  - cd web-audio-api
  - ls
  - pwd
  - bower install
  - cd ../..

script:
  # - polymer build
  # - cd ..
  - firebase deploy --token $FIREBASE_TOKEN
