language: node_js

node_js:
  - node

before_install:
  - npm i -g polymer-cli
  - npm i -g firebase-tools
  - cd public
  - git clone https://github.com/interlucid/web-audio-api

install:
  - cd web-audio-api
  - ls
  - pwd
  - npm install

script:
  - polymer build
  - cd ../..
  - firebase deploy --token $FIREBASE_TOKEN
